name: PHP APP
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: CI/CD-PHPAPP
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          whoami
          cd /home/UniqueVistors-main/UniqueVistors-main
          sudo git pull origin main
          sudo docker-compose up --build -d